destination: ../build
port: 5000
site: Naut Konceptutveckling
baseurl: ""
url: "http://nautkoncept.se"
lang: sv-se
# Build settings
markdown: kramdown
thumb: naut.jpg
layout: naut
author: Morgan A Ray
company: wimse
company_desc: wimse är en komplett och kreativ webbbyrå belägen i göteborg. Vi hjälper företag till ökad lönsamhet genom att förbättra och utveckla afärsmodeller. Genom kreativt tänkande, nyskapande idéer och med tekniskt lösningar kan vi tillsammans förbättra din verksamhet. Vi skapar plattformat som tilltalar och stärker din profilering och närvaro på Internet.
company_url: http://wimse.se

prose:
    siteurl: "https://nautkoncept.github.io"
    media: "assets/themes/naut/img"
    ignore:
        - index.html
        - feed.xml
        - _config.yml
        - CNAME
        - css
    metadata:
        _posts/vids:
            - name: "title"
              field:
                  element: "text"
                  label: "title"
            - name: "img"
              field:
                  element: "text"
                  value: ""
                  label: "Bild"
                  help: "glöm inte att du måste ange filendelsen."
                  placeholder: "ex.jpg"
            - name: "yt-video-id"
              field:
                  element: "text"
                  value: ""
                  label: "Youtube ID"
                  help: "är sista delen i länken, ex: (https://www.youtube.com/watch?v=m4pMRtSzjSo)."
                  placeholder: "m4pMRtSzjSo"
            - name: "description"
              field:
                  element: "text"
                  value: ""
                  label: "Beskrivning"
                  help: "själva texten."
                  placeholder: "En liten flicka som en gång fått en röd mössa av sin mormor skickas av sin mor med en korg med matvaror till mormodern."
            - name: "cred"
              field:
                  element: "text"
                  value: ""
                  label: "Cred"
                  help: "is due"
                  placeholder: "RAY THE MAN"
            - name: "foto"
              field:
                  element: "text"
                  value: ""
                  label: "Foto"
                  help: "Vem har skött kameran?"
                  placeholder: "Pelle Svanslös"
