destination: ../build
port: 5000
site: Naut Konceptutveckling
baseurl: ""
url: "http://nautkoncept.se"
lang: sv-se
# Build settings
markdown: kramdown
thumb: naut.jpg
layout: naut
author: Morgan A Ray
company: wimse
company_desc: wimse är en komplett och kreativ webbbyrå belägen i göteborg. Vi hjälper företag till ökad lönsamhet genom att förbättra och utveckla afärsmodeller. Genom kreativt tänkande, nyskapande idéer och med tekniskt lösningar kan vi tillsammans förbättra din verksamhet. Vi skapar plattformat som tilltalar och stärker din profilering och närvaro på Internet.
company_url: http://wimse.se

prose:
    siteurl: "https://nautkoncept.github.io"
    media: "assets/themes/naut/img"
    ignore:
        - index.html
        - feed.xml
        - _config.yml
        - CNAME
        - css
    metadata:
        _posts:
            - name: "title"
              field:
                  element: "text"
                  label: "title"
