

####################################################### prose.io configurations
prose:
  rooturl: ''
  siteurl: 'http://nautkoncept.se/'
  relativeLinks: 'http://nautkoncept.se/links.jsonp'
  ignore:
    - index.html
    - _config.yml
    - /_layouts
    - /_includes
    - _data
    - css
    - 404.html
    - CNAME
  metadata:
    _posts:
      - name: "category"
        field:
          element: "multiselect"
          label: "Kategori"
          placeholder: "V채lj kategorier"
          options:
            - name: "Case"
              value: "case"
            - name: "Education"
              value: "edu"
            - name: "Video p책 framsida"
              value: "pinned-video"
            - name: "Post p책 framsida"
              value: "pinned-post"
      - name: "published"
        field:
          element: "checkbox"
          label: "Publicerad"
          value: "true"
      - name: "title"
        field:
          element: "text"
          type: "text"
      - name: "date"
        field:
          element: "hidden"
          value: CURRENT_DATETIME
      - name: "layout"
        field:
          element: "hidden"
          value: post_full
      - name: "vimeo-embed"
        field:
          element: "text"
          label: "Vimeo Embedding Code"
          help: "Klistra in allt mellan &lt;iframe&gt;...&lt;/iframe&gt;."
      - name: "yt-video-id"
        field:
          element: "text"
          label: "Youtube ID"
          help: "youtube id finner du i adressf채ltet efter v="
